#!/usr/bin/env python3
import subprocess, os

os.makedirs("final", exist_ok=True)

scene_files = sorted(os.listdir("scenes_mp4"))
with open("concat.txt", "w") as f:
    for filename in scene_files:
        f.write(f"file 'scenes_mp4/{filename}'\n")

subprocess.run([
    "ffmpeg", "-y",
    "-f", "concat",
    "-safe", "0",
    "-i", "concat.txt",
    "-c", "copy",
    "final/output.mp4"
])

print("Final video: final/output.mp4")
